"""Canonical default audio fixtures generated by tools/audio/generate.py."""

from pathlib import Path

GENERATED = Path(__file__).resolve().parents[1] / "audio" / "generated"


def standard_audio(rate=48000, group=False):
    mode, duration = ("group", "2p5") if group else ("repeat", "15p5")
    return GENERATED / f"standard_{mode}_{rate}hz_{duration}s.wav"


def wide_audio(rate=48000):
    return GENERATED / f"wide_repeat_{rate}hz_15p5s.wav"
