#ifndef BOARD_MEMORY_H
#define BOARD_MEMORY_H
#include "app_board_config.h"

/* Application-owned, non-cacheable SDRAM. Keep addresses stable across
 * refactors; BSP/CubeMX defaults and MPU setup are checked by main.c. */
#define BOARD_SDRAM_BASE             0xC0000000U
#define BOARD_SDRAM_BYTES            0x00800000U
#define BOARD_LCD_WIDTH             480U
#define BOARD_LCD_HEIGHT            272U
#define BOARD_LCD_FRAME_BYTES       (BOARD_LCD_WIDTH * BOARD_LCD_HEIGHT * 4U)
#define BOARD_LCD_FRAME_A           0xC0000000U
#define BOARD_LCD_FRAME_B           0xC0080000U
#define BOARD_AUDIO_DMA_BASE        0xC0100000U
#define BOARD_AUDIO_DMA_WORDS       (APP_AUDIO_HALF_FRAMES * 4U)
#define BOARD_AUDIO_DMA_BYTES       (BOARD_AUDIO_DMA_WORDS * 2U)
#define BOARD_CAPTURE_BLOCKS        1000U
#define BOARD_CAPTURE_PCM_BASE      0xC0200000U
#define BOARD_CAPTURE_PCM_BYTES     (BOARD_CAPTURE_BLOCKS * APP_AUDIO_HALF_FRAMES * 4U)
#define BOARD_CAPTURE_ANCHORS_BASE  0xC0520000U
#define BOARD_CAPTURE_ANCHOR_BYTES  24U
#define BOARD_CAPTURE_ANCHORS_BYTES (BOARD_CAPTURE_BLOCKS * BOARD_CAPTURE_ANCHOR_BYTES)
#define BOARD_CAPTURE_LOG_BASE      0xC0530000U
#define BOARD_CAPTURE_LOG_BYTES     131072U
#define BOARD_CAPTURE_HEADER_BASE   0xC0550000U
#define BOARD_CAPTURE_HEADER_BYTES  4096U
#define BOARD_SD_BUFFER_BASE        0xC0551000U
#define BOARD_SD_BUFFER_BYTES       512U

/* Address-ordered regions: these checks prove containment and no overlap.
 * Include bytes actually used, not only gaps reserved between addresses. */
#if BOARD_LCD_FRAME_A < BOARD_SDRAM_BASE || \
    BOARD_LCD_FRAME_A + BOARD_LCD_FRAME_BYTES > BOARD_LCD_FRAME_B || \
    BOARD_LCD_FRAME_B + BOARD_LCD_FRAME_BYTES > BOARD_AUDIO_DMA_BASE || \
    BOARD_AUDIO_DMA_BASE + BOARD_AUDIO_DMA_BYTES > BOARD_CAPTURE_PCM_BASE || \
    BOARD_CAPTURE_PCM_BASE + BOARD_CAPTURE_PCM_BYTES > BOARD_CAPTURE_ANCHORS_BASE || \
    BOARD_CAPTURE_ANCHORS_BASE + BOARD_CAPTURE_ANCHORS_BYTES > BOARD_CAPTURE_LOG_BASE || \
    BOARD_CAPTURE_LOG_BASE + BOARD_CAPTURE_LOG_BYTES > BOARD_CAPTURE_HEADER_BASE || \
    BOARD_CAPTURE_HEADER_BASE + BOARD_CAPTURE_HEADER_BYTES > BOARD_SD_BUFFER_BASE || \
    BOARD_SD_BUFFER_BASE + BOARD_SD_BUFFER_BYTES > BOARD_SDRAM_BASE + BOARD_SDRAM_BYTES
#error Application SDRAM buffers overlap or exceed SDRAM
#endif
#if ((BOARD_LCD_FRAME_A | BOARD_LCD_FRAME_B | BOARD_AUDIO_DMA_BASE | \
      BOARD_CAPTURE_PCM_BASE | BOARD_CAPTURE_ANCHORS_BASE | BOARD_CAPTURE_LOG_BASE | \
      BOARD_CAPTURE_HEADER_BASE | BOARD_SD_BUFFER_BASE) & 31U) != 0
#error Application SDRAM buffers must be 32-byte aligned
#endif
#if BOARD_SDRAM_BYTES != 0x00800000U || (BOARD_SDRAM_BASE & (BOARD_SDRAM_BYTES - 1U)) != 0
#error Update and verify the 8 MB MPU region before changing SDRAM geometry
#endif
#if BOARD_CAPTURE_HEADER_BYTES != 4096U || BOARD_CAPTURE_ANCHOR_BYTES != 24U || BOARD_SD_BUFFER_BYTES != 512U
#error RNG1 record sizes and SD sector size must remain compatible with their formats
#endif
#endif
