"""Explicitly export DC-removed STANDARD/WIDE C templates from a matching WAV."""

import argparse
from array import array
import hashlib
from pathlib import Path
import sys
import wave


def export_template(source, output, profile, rate):
    if rate != 48000:
        raise ValueError("only 48000 Hz templates are supported")
    with wave.open(str(source), "rb") as wav:
        if (wav.getframerate(), wav.getnchannels(), wav.getsampwidth()) != (rate, 1, 2):
            raise ValueError("expected matching sample rate, mono, PCM16")
        pcm = array("h", wav.readframes(wav.getnframes()))
    if sys.byteorder != "little":
        pcm.byteswap()
    pulse = rate * 32 // 1000
    step = rate * (40 if profile == "standard" else 36) // 1000
    if len(pcm) < step + pulse:
        raise ValueError("WAV is too short for both chirp pulses")
    guard = "RANGE_TEMPLATE_H" if profile == "standard" else "RANGE_TEMPLATE_WIDE_H"
    lines = ["/* Generated by tools/audio/export_template.py; do not edit.",
             f" * WAV: {source.name}; SHA256: {hashlib.sha256(source.read_bytes()).hexdigest()} */",
             f"#ifndef {guard}", f"#define {guard}", "#include <stdint.h>"]
    for name, samples in zip(("Up", "Down"), (pcm[:pulse], pcm[step:step + pulse])):
        mean = sum(samples) / len(samples)
        values = [round(value - mean) for value in samples]
        if any(value < -32768 or value > 32767 for value in values):
            raise ValueError("DC-removed template exceeds PCM16 range")
        lines += [f"#define RANGE_{name.upper()}_ENERGY {float(sum(x*x for x in values)):.1f}f",
                  f"#define RANGE_{name.upper()}_COARSE_ENERGY {float(sum(x*x for x in values[::3])):.1f}f",
                  f"static const int16_t range{name}[{pulse}] = {{"]
        lines += ["  " + ", ".join(map(str, values[i:i + 16])) + "," for i in range(0, pulse, 16)]
        lines.append("};")
    lines.append("#endif")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", choices=("standard", "wide"), default="standard")
    parser.add_argument("--sample-rate", type=int, choices=(48000,), default=48000)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True, help="explicit C header destination")
    args = parser.parse_args(argv)
    try:
        if args.output.suffix.lower() != ".h":
            raise ValueError("output must have a .h extension")
        export_template(args.input, args.output, args.profile, args.sample_rate)
    except (ValueError, OSError, wave.Error) as error:
        parser.error(str(error))
    print(f"Saved template: {args.output.resolve()}")


if __name__ == "__main__":
    main()
